#!/bin/bash
# Start learning test with one robot with supervisor.

python start.py --output-directory output --restore-directory restore --population-size 15 --tournament-size 5 --eval-time 300 --test-bot "../testBots/gecko"

