#!/bin/bash
# Start learning test with one robot with supervisor.

python start.py --output-directory output --restore-directory restore --population-size 10 --num-children 5 --tournament-size 2 --eval-time 10 --test-bot "../testBots/spider"

